# Use root/example as user/password credentials
version: '3.7'

services:

  flask:
    build: ./Nestmatics-backend
    container_name: flask
    restart: always
    environment:
      - APP_NAME=Nestmatics
      - DB_USERNAME=root
      - DB_PASWD=example
      - DB_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - mongo
      - flask
      - mongo-express
    ports:
      - "80:80"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    expose:
      - 27017
    volumes:
      - ./mongo_data:/data/db


  mongo-express:
    image: mongo-express
    container_name: mongoexpress
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_SITE_BASEURL: /mongoadmin
    depends_on:
      - mongo
      - flask
    ports:
      - "8081:8081"

